// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace WorklabsMx.iOS
{
	public partial class CeldaNoDetalleVenta : UITableViewCell
	{
		public CeldaNoDetalleVenta (IntPtr handle) : base (handle)
		{
		}

        internal void UpdateCell(bool existeConeccion)
        {
            if (existeConeccion)
            {
                lblNoInfo.Text = "No hay productos en tu carrito";
            }
            else
            {
                lblNoInfo.Text = "No tienes acceso a una conexión de Internet";
            }
        }
	}
}
