// This file has been autogenerated from a class added in the UI designer.

using System;
using WorklabsMx.Models;
using UIKit;
using BigTed;
using WorklabsMx.iOS.Helpers;

namespace WorklabsMx.iOS
{
	public partial class VentaDetalleHeader : UITableViewCell
	{

       // public event EventHandler CanjearCupon;

		public VentaDetalleHeader (IntPtr handle) : base (handle)
		{
            
		}

        internal void UpdateCell(double Subtotal, double Impuesto, double Total, PromocionModel DatosDescuento)
        {
            StyleHelper.Style(this.btnUsarCupon.Layer);
            this.lblTotal.Text = Total.ToString("C");
            this.lblImpuesto.Text = Impuesto.ToString("C");
            this.lblSubtotal.Text = Subtotal.ToString("C");
            if (DatosDescuento.Descuento_Id != null)
            {
                var descuento = (Subtotal * (double)DatosDescuento.Descuento_Porcentaje);
                descuento = descuento * 1.16;

                this.lblDescuento.Text = descuento.ToString("C");
                this.lblLeyendaTotalDescuento.Hidden = false;
                this.lblTotalConDescuento.Hidden = false;
                this.lblTotalConDescuento.Text = (Total - descuento).ToString("C");
                BTProgressHUD.Dismiss();
            }

        }

    }
}
