// This file has been autogenerated from a class added in the UI designer.

using System;
using UIKit;
using WorklabsMx.iOS.Models;
using WorklabsMx.iOS.Helpers;

namespace WorklabsMx.iOS
{
	public partial class CeldaVentaDetalle : UITableViewCell
	{
		public CeldaVentaDetalle (IntPtr handle) : base (handle)
		{
		}

        internal void UpdateCell(CarritoCompras carrito)
        {
            StyleHelper.Style(this.vwVistaDetalleVenta.Layer);
            this.lblCantidad.Text = carrito.Cantidad.ToString();
            this.lblTotalPagar.Text = carrito.TotalPagar;
            this.lblNombreProducto.Text = carrito.Nombre;
        }
	}
}
