// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace WorklabsMx.iOS
{
	public partial class CommentsHeaderCell : UITableViewCell
	{
		public CommentsHeaderCell (IntPtr handle) : base (handle)
		{
		}
	}
}
