// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using WorklabsMx.iOS.Models;
using System.Collections.Generic;
using BigTed;
using System.Threading.Tasks;
using WorklabsMx.Controllers;
using WorklabsMx.iOS.Helpers;

namespace WorklabsMx.iOS
{
	public partial class TabBarDetalleVenta : UITabBarController
	{

        List<CarritoCompras> listaProductos = new List<CarritoCompras>();
        int numb = 0;

        public TabBarDetalleVenta (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            var barViewControllers = this.ViewControllers;
            var vistaMembresias = (TableViewMembresia)barViewControllers[1];
            vistaMembresias.Membresias = new PickerItemsController().GetMembresias();
        }

        partial void btnCarrito_Touch(UIBarButtonItem sender)
        {
            var barViewControllers = this.ViewControllers;
            var vistaProductos = (CarritoProductos)barViewControllers[0];
            listaProductos = vistaProductos.ObtenerPreordenProductos();

            var VistaMembresias = (TableViewMembresia)barViewControllers[1];
            var listaMembresias = VistaMembresias.ObtenerPreordenMembresias();

            foreach (CarritoCompras preordenMembresia in listaMembresias)
            {
                if (listaProductos.Find(x => x.Id == preordenMembresia.Id) == null)
                {
                    listaProductos.Add(preordenMembresia);
                }
            }

            if (listaProductos.Count == 0)
            {
                new MessageDialog().SendToast("Aun no haz seleccionado un producto o membresía");
            }
            else 
            {
                this.PerformSegue("detalleVenta", null);
            }
           

        }

        public async override void ItemSelected(UITabBar tabbar, UITabBarItem item)
        {
            numb = numb + 1;
            if (item.Title == "Membresías" && numb == 1)
            {
                BTProgressHUD.Show(status: "Cargando Membresías");
                await Task.Delay(100);
            }
        }

        public override void PrepareForSegue(UIStoryboardSegue segue, NSObject sender)
        {
            
            if (segue.Identifier == "detalleVenta")
            {
                var postCommentView = (VentaDetalleTableViewController)segue.DestinationViewController;
                postCommentView.PreordenProductos = listaProductos;
            }
        }

	}
}
