// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace WorklabsMx.iOS
{
	public partial class VentaDetalle : UITableViewController
	{
		public VentaDetalle (IntPtr handle) : base (handle)
		{
		}
	}
}
